#!/bin/scheduler.mex

# reboot runs once at startup
@reboot echo scheduler started

# service runs once at startup and is restarted if it exits
# a retry count is implemented to prevent infinite restart loops
@service resolved -v -i 0 -s 192.203.230.10
@service shortcutd

# every runs at the specified interval
every 10 minutes dhcp -i 0

# shortcuts get registered as global keybindings
shortcut Strg+r pwr reset
shortcut Strg+p pwr off
shortcut Strg+a echo Hello World!
