# Build configuration
# Desktop
# DESKTOP = 0
# FIRESTORM = 0
# End Desktop

# Syscalls
SYS_OPEN_ID = 1
SYS_CLOSE_ID = 2
SYS_READ_ID = 3
SYS_WRITE_ID = 4
SYS_FILESIZE_ID = 5
SYS_DELETE_ID = 6
SYS_MKDIR_ID = 7
SYS_DIR_AT_ID = 8
SYS_TOUCH_ID = 9
SYS_DELETE_DIR_ID = 10
SYS_FS_AT_ID = 11
SYS_ASYNC_GETC_ID = 12
SYS_EXIT_ID = 13
SYS_MMAP_ID = 14
SYS_SPAWN_ID = 15
SYS_GET_PROC_INFO_ID = 16
SYS_YIELD_ID = 17
SYS_ENV_ID = 18
SYS_MMMAP_ID = 19
SYS_VMODE_ID = 20
SYS_VPOKE_ID = 21
SYS_VCURSOR_ID = 22
SYS_ICMP_ID = 23
SYS_SOCK_CONNECT_ID = 26
SYS_SOCK_DISCONNECT_ID = 27
SYS_SOCK_SEND_ID = 28
SYS_SOCK_RECV_ID = 29
SYS_SOUND_RUN_ID = 30
SYS_TIME_ID = 31
SYS_SET_COLOR_ID = 32
SYS_ASYNC_GETARRW_ID = 33
SYS_VCURSOR_GET_ID = 34
SYS_TASK_LIST_GET_ID = 35
SYS_KILL_ID = 36
SYS_VPEEK_ID = 37
SYS_RAMINFO_ID = 38
SYS_MOUSE_INFO_ID = 39
SYS_TRUNCATE_ID = 40
SYS_TIME_MS_ID = 41
SYS_THREAD_ID = 42
SYS_SET_TERM_ID = 43
SYS_IPV4_RESOLVE_ROUTE_ID = 44
SYS_SOCK_SET_LOCAL_PORT_ID = 45
# End Syscalls

# End Build configuration

