[build]
target = "./i686-unknown-microos.json"

[target.x86_64]
rustflags = ["--emit=obj", "-C", "relocation-model=static", "-Z", "plt=no"]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]