name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: sudo apt update && sudo apt install xorriso mtools -y
    - name: get resources
      run: make res
    - name: make
      run: make iso
    - uses: actions/upload-artifact@v2
      with:
        name: "iso"
        path: | 
            cdrom.iso
