name: Release (fst)

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: install tools
      run: sudo apt update && sudo apt install xorriso mtools grub-pc-bin zip gcc-i686-linux-gnu -y
    - name: make
      run: make preset_fst && make iso libs.zip
    - uses: actions/upload-artifact@v2
      with:
        name: "build"
        path: | 
          cdrom.iso
          libs.zip
