name: Release (foxtail)

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: sudo apt update && sudo apt install xorriso mtools grub-pc-bin zip gcc-i686-linux-gnu -y
    - name: make
      run: make libs.zip
    - name: build foxtail
      run: cd foxtail; bash build.sh; cd ..; make iso
    - uses: actions/upload-artifact@v2
      with:
        name: "build"
        path: | 
          cdrom.iso
          libs.zip