PROGRAM = vdoom.elf

include ../../build/program.mk

AUTHOR="glowman554, id Software"

CFLAGS += -DDOOM_IMPLEMENT_MALLOC -DDOOM_IMPLEMENT_FILE_IO -DDOOM_IMPLEMENT_EXIT -DDOOM_IMPLEMENT_GETENV

EXTRA_OBJS = res/libs/libwindow.o